### ISSUE TITLE
Festive creeper shoots you a tnt when hit even from far away

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#104]

**Comment by Darkmega18** [comment]
I actually find this rather cool. cause I find that when there are festives down on the ground and I'm gliding over head on an openblocks glider they start launching their tnts into the air to try to flak cannon me out of the sky. it's actually really cool in a somewhat terrifying way, not that the blasts hit very often due to the time delay.

**Comment by Daveyx0** [comment]
Fixed in next version together with some buffs

**Comment by Darkmega18** [comment]
:o buuuuffs. Anti-air combat with actual festive fire works? :D
