### ISSUE TITLE
Dodo meat has excessive saturation

### ISSUE THREAD

**Issue by Lykrast** [Daveyx0/PrimitiveMobs#112]
While it may be intentional given Cooked Dodo is supposed to be `the best food compared to vanilla Minecraft`, it still gives excessive amount of saturation compared to both vanilla and modded foods, as seen here through AppleSkin:

![image](https://user-images.githubusercontent.com/8684850/44002929-21c722b2-9e4b-11e8-9e39-198ecab41f1a.png)
![image](https://user-images.githubusercontent.com/8684850/44002932-279ae9d0-9e4b-11e8-9149-89e6371d87c9.png)

Vanilla beef for comparaison:
![image](https://user-images.githubusercontent.com/8684850/44002940-3ef9e41e-9e4b-11e8-97cf-57ad975690e4.png)
![image](https://user-images.githubusercontent.com/8684850/44002942-444b01dc-9e4b-11e8-9458-1d2ac0436079.png)

**Comment by Daveyx0** [comment]
The saturation is as high as the one from a golden carrot if I remember correctly. It's tricky to obtain this meat after all; unless you think otherwise, which is valid critism. The thing is that it's difficult to motivate the player to go through the effort of the elaborate breeding mechanics without this as a reward. I think it's fine as it is; unless I see people somehow exploit this to the max then I might nerf this in the future. Thanks for the feedback, Lykrast!
