### ISSUE TITLE
[Forge 2768] [MC-1.12.2] Ticking Entity BoP/PrimitiveMobs Crash

### ISSUE THREAD

**Issue by Excaliburning** [Daveyx0/PrimitiveMobs#127]
Hello !

I've posted an issue on BoP about a ticking entity crash which involves BoP and some Primitive/Rocket Creepers.

[Here's the link with crash logs.](https://github.com/Glitchfiend/BiomesOPlenty/issues/1324)

**Comment by Daveyx0** [comment]
Thanks for the report. Sorr6 for the late answer. Should be fixed in the 1.2 alpha!

**Comment by QueenBonnydust** [comment]
> Thanks for the report. Sorr6 for the late answer. Should be fixed in the 1.2 alpha!

Sad to report this is NOT fixed in 1.2 alpha as just trialled with my server. This error occurs with rocket creeper and the Tundra biome for me, hopefully the screen shots will help.


![2018-12-17_18 48 00](https://user-images.githubusercontent.com/41415176/50076233-dbbe2900-022c-11e9-8c75-d7789a655914.png)
![2018-12-17_18 48 19](https://user-images.githubusercontent.com/41415176/50076236-dc56bf80-022c-11e9-9d2f-5674e75442b8.png)
![2018-12-17_18 48 23](https://user-images.githubusercontent.com/41415176/50076237-dc56bf80-022c-11e9-879b-376bc8d376e8.png)

[bop primitive mobs error.txt](https://github.com/Daveyx0/PrimitiveMobs/files/2685098/bop.primitive.mobs.error.txt)

**Comment by Excaliburning** [comment]
> 
> 
> Thanks for the report. Sorr6 for the late answer. Should be fixed in the 1.2 alpha!

Thanks for looking into this, even if it's late it's good as long as you're on it :)

> 
> 
> Sad to report this is NOT fixed in 1.2 alpha as just trialled with my server. This error occurs with rocket creeper and the Tundra biome for me, hopefully the screen shots will help.
> [bop primitive mobs error.txt](https://github.com/Daveyx0/PrimitiveMobs/files/2685098/bop.primitive.mobs.error.txt)

Thanks for your feedback as I can't provide any for now, our server has been put on hold because we need to do a lot of tweaking and customization of config files, this is December and we definitely don't have such time, the server being offline I can't test if it's fixed or not. Glad to see someone verified it !

**Comment by Daveyx0** [comment]
Thanks. Will check it out. I was sure I fixed this.... hmmm.

**Comment by Daveyx0** [comment]
Ok, I found the issue. Fix will be in the next version :) Gotta fix some additional bugs before I upload that though.
