### ISSUE TITLE
[Bug] Festive Creeper  appears even if it is disabled

### ISSUE THREAD

**Issue by KorDum** [Daveyx0/PrimitiveMobs#30]
But fully invisible, it's throw TNT.

**Comment by Daveyx0** [comment]
Are you using the newest version? 1.1.4b beta? 
Did you restart the game after disabling the creeper?
Was it a creeper that perhaps already spawned before disabling it?

This bug should be fixed in the latest version afaik. After running various debug tests; the entity never spawns for me when disabling and restarting.

**Comment by KorDum** [comment]
Yes, in 1.1.4b fixed. Thanks!
