### ISSUE TITLE
Game crash, possibly a conflict with Chococraft

### ISSUE THREAD

**Issue by faeldray** [Daveyx0/PrimitiveMobs#34]
My game just crashed without warning and judging by the crash report, it might be because a brain slime tried to attack a chocobo. I also can't get back into that save without it crashing so I had to restore from a backup.

I'm turning off the option for brain slimes to attack animals to see if that will help.

https://pastebin.com/2SGS1Tct

**Comment by Daveyx0** [comment]
It appears the Chocobo only expects Players to be on top of it, which is odd. I recommend posting this to the Chococraft issue tracker and asking for an entity check for ridden entities. That should solve it. Otherwise you can disable the hostility yeh; however Brain Slimes still attach on contact, which I still need to add to the config.

**Comment by Daveyx0** [comment]
I will close this for now, as this is not an issue for PM. However, version 1.1.5b beta will make it so the hostility option for Brain Slimes also prevents random attaching to mobs.

**Comment by faeldray** [comment]
Thanks for doing that. It looks like [someone already reported the issue](https://github.com/Xalcon/ChocoCraft3/issues/23) to Chococraft (and even made a fix), but it just hasn't been added to the mod yet.
