### ISSUE TITLE
UltimateUnicorn conflict crash

### ISSUE THREAD

**Issue by EightBlade** [Daveyx0/PrimitiveMobs#55]
I'm having this issue when ultimate unicorn mobs and brain slimes are nearby
https://pastebin.com/Awbjsi4t

**Comment by Daveyx0** [comment]
This is another instance of the entity not expecting anything but a player to be able to mount it. You can disable the Brain Slime aggressiveness option in the config. Otherwise the creator of UltimateUnicorn needs to implement a simple check for the unicorn to see if what is riding it is indeed a player. I cannot check if an entity only wants players to mount it apart maybe through unreliable means. Thanks for reporting btw ;)

**Comment by Daveyx0** [comment]
Gonna close this for now.
